services:
  mongo:
    image: mongo:8
    container_name: mongo-toppilife-op
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: toppilife_oldpeople
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo-data-toppilife_oldpeople:/data/db

  app:
    build: .
    container_name: toppilife-oldpeople
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data-toppilife_oldpeople:
